language: node_js
node_js:
  - 6
cache:
  directories:
  - docs/vendor/bundle
  - node_modules
  - $HOME/.yarn-cache
before_install:
- |
    sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
    echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
    sudo apt-get update -qq
    sudo apt-get install -y -qq yarn
    yarn --version
install:
- |
    yarn install
script:
- |
    yarn run lint
#   Disabled until testing is fixed
#   yarn run test:lcov
